export const ARTICLE_LIST = [
  {
    mainTitle: 'SubTitle',
    dateStr: '2021.04.19',
    description: `해당 날짜의 영상들에 대한 설명`,
    videos: [
      `https://www.youtube.com/embed/luPj1uU3CWw`,
      `https://www.youtube.com/embed/9wTpF-cLjm8`,
      `https://www.youtube.com/embed/lERa_3TznAw`,
      `https://www.youtube.com/embed/Q61Zvk8OyU8`,
      `https://www.youtube.com/embed/VEtA-UEm-rU`,
      `https://www.youtube.com/embed/PbXwnGbDrx0`,
      `https://www.youtube.com/embed/cig842ZL_0Y`,
      `https://www.youtube.com/embed/JwW1pMRlvI8`,
      `https://www.youtube.com/embed/h_OwoNEP3WQ`,
      `https://www.youtube.com/embed/ICoT8LS0jTo`,
      `https://www.youtube.com/embed/T4OOdafezvc`,
      `https://www.youtube.com/embed/DEyL-g5nt60`,
    ],
  },
  {
    mainTitle: '샘플이 더 필요해~',
    dateStr: '2021.04.20',
    description: `다른 날짜 찍은 것도 유튜브로 올려줘!`,
    videos: [
      `https://www.youtube.com/embed/luPj1uU3CWw`,
      `https://www.youtube.com/embed/9wTpF-cLjm8`,
      `https://www.youtube.com/embed/lERa_3TznAw`,
      `https://www.youtube.com/embed/Q61Zvk8OyU8`,
      `https://www.youtube.com/embed/VEtA-UEm-rU`,
      `https://www.youtube.com/embed/PbXwnGbDrx0`,
      `https://www.youtube.com/embed/cig842ZL_0Y`,
      `https://www.youtube.com/embed/JwW1pMRlvI8`,
      `https://www.youtube.com/embed/h_OwoNEP3WQ`,
      `https://www.youtube.com/embed/ICoT8LS0jTo`,
      `https://www.youtube.com/embed/T4OOdafezvc`,
      `https://www.youtube.com/embed/DEyL-g5nt60`,
    ],
  },
]
